trigger:
- master

pr: none

pool:
  name: Default
  demands:
  - Agent.Name -equals BEAT5

steps:
- checkout: self

- bash: |
    set -eu
    mkdir -p /home/ql07sq/flatris-lab
    
    
    echo "Deployment vanaf GitHub geslaagd op $(hostname)"
displayName: Deploy GitHub-bestand naar Pi