trigger:
- master

pr: none

pool:
  name: Default
  demands:
  - Agent.Name -equals BEAT5

steps:
- checkout: self

- bash: |
    set -eu
    mkdir -p /home/ql07sq/github-demo
    cp err.log /home/ql07sq/github-demo/err.log
    
    echo "Deployment vanaf GitHub geslaagd op $(hostname)"
    
  displayName: Deploy GitHub-bestand naar Pi